### PR TITLE
GPS Coordinate Fix

### PR DESCRIPTION
**Pull request by RlonRyan**
Patch to correct rounding issue, as demonstrated in #1505.

### CODE REVIEW

**Comment by RlonRyan** [comment]
Wait... I might have messed up on the logic on this one... Might want to hold on to this until I can get thorough testing done.

**Comment by RlonRyan** [comment]
Yeah. I got the logic backwards on this one... In any case the original code should have been fine, meaning the issue warrants further investigation as to where the error is coming from.

**Comment by olee** [comment]
Actually correct would be `(int) Math.floor(coordinate)`.

**Comment by RlonRyan** [comment]
@Olee... Sorry, but that would be redundant as the return type of Math.floor is an int.

Anyways, the reason it gave me so much trouble, is due to the fact that what is reported to happen shouldn't be happening, based on the code.

After all, the overall goal is to report the player's coordinates in a discrete - that is non-continuous - manner. The coordinates should just be the same with the decimal portion lopped off. This is the same as rounding to the direction of zero. Such is what the typecast (int) does. Therefore, the reported behavior should not be happening on our end.

That being said, I need to test this a whole lot more... but this could be a lower-lying issue, perhaps with the way the f5 screen displays the location... It will be worthwhile to compare this command with a map mod...

**Comment by olee** [comment]
@RlonRyan tztztz much you have to learn... it returns double
````
  public static double floor(double paramDouble)
  {
    return StrictMath.floor(paramDouble);
  }

**Pull request closed without merging**
