### PR TITLE
/portal list, /portal create <dimension>

### PR DESCRIPTION
**Pull request by BuggeringHell**
Removed height and width from create command, added dimension
Added portal list command that outputs basic portal.toString for loop

### CODE REVIEW

**Comment by luacs1998** [comment]
Your code does not compile. Please fix and test.

**Comment by BuggeringHell** [comment]
It compiles fine for me. The portals go to other dimensions fine. What errors are you getting?

**Comment by luacs1998** [comment]
Uggh... Travis hates PRs lately...

@olee your call

**Comment by olee** [comment]
I'm going to take care of this - there's some stuff to the portal command I wanted to adjust anyway.
But @luacs1998 you need to take a look at #1333

**Pull request closed without merging**
